In [10]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
dataset = pd.read_csv("./sample_dataset.csv")

In [3]:
dataset.head()

            Name  Gender        City Passed
0  Aayush Sharma    Male   Kathmandu    Yes
1      Sita Rana  Female     Pokhara     No
2     Raju Thapa    Male    Lalitpur    Yes
3       Nisha KC  Female   Bhaktapur    Yes
4     Binod Lama    Male  Biratnagar     No

In [4]:
dataset.isnull().sum()

Name      0
Gender    0
City      0
Passed    0
dtype: int64

In [21]:
df_label = dataset.copy()


# label encoding of the Gender and passed column
le = LabelEncoder()
df_label["Gender_Encoded"] = le.fit_transform(df_label["Gender"])
df_label["Passed_Encoded"] = le.fit_transform(df_label["Passed"])
df_label.drop(["Name","Gender","City","Passed"], inplace=True, axis=1)
df_label

    Gender_Encoded  Passed_Encoded
0                1               1
1                0               0
2                1               1
3                0               1
4                1               0
5                0               1
6                1               1
7                0               0
8                1               1
9                0               1
10               1               0
11               0               1
12               1               1
13               0               0
14               1               1
15               0               1
16               1               0
17               0               1
18               1               1
19               0               0

In [19]:
# one - hot encodeing of the name and city
# df_endcoded = pd.get_dummies(df_label,columns=["City", "Name"])
# df_endcoded

In [26]:

sd_scaler = StandardScaler()
df_standard_scaled = sd_scaler.fit_transform(df_label)
pd.DataFrame(df_standard_scaled, columns=["Gender_Encoded", "Passed_Encoded"])

    Gender_Encoded  Passed_Encoded
0              1.0        0.733799
1             -1.0       -1.362770
2              1.0        0.733799
3             -1.0        0.733799
4              1.0       -1.362770
5             -1.0        0.733799
6              1.0        0.733799
7             -1.0       -1.362770
8              1.0        0.733799
9             -1.0        0.733799
10             1.0       -1.362770
11            -1.0        0.733799
12             1.0        0.733799
13            -1.0       -1.362770
14             1.0        0.733799
15            -1.0        0.733799
16             1.0       -1.362770
17            -1.0        0.733799
18             1.0        0.733799
19            -1.0       -1.362770

In [27]:
minmax_scaler = MinMaxScaler()
minmax_scaled = minmax_scaler.fit_transform(df_label)
pd.DataFrame(minmax_scaled, columns=["Gender_Encoded", "Passed_Encoded"])

    Gender_Encoded  Passed_Encoded
0              1.0             1.0
1              0.0             0.0
2              1.0             1.0
3              0.0             1.0
4              1.0             0.0
5              0.0             1.0
6              1.0             1.0
7              0.0             0.0
8              1.0             1.0
9              0.0             1.0
10             1.0             0.0
11             0.0             1.0
12             1.0             1.0
13             0.0             0.0
14             1.0             1.0
15             0.0             1.0
16             1.0             0.0
17             0.0             1.0
18             1.0             1.0
19             0.0             0.0